name: RunUnitTest

on:
  push:
    branches:
      - exam
  pull_request:
    branches:
      - exam

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Catch2
      run: |
        wget https://github.com/catchorg/Catch2/releases/download/v2.13.6/catch.hpp -O include/catch.hpp

    - name: Build and Run Tests
      working-directory: test
      run: |
        make sinUnitTest
        make runsinUnitTest
        make sinRegrTest
        make runsinRegrTest
